# rubocop:disable all
# typed: strict
# frozen_string_literal: true

# DO NOT EDIT
# Generated by: `protoc-gen-nuevo`
# Source: compatible.proto

require "google/protobuf"
# @@protoc_insertion_point(requires)

pool = Google::Protobuf::DescriptorPool.generated_pool
begin
  descriptor_data =
    "\n\x10compatible.proto\x12\x1Dasync.grpc.compatible.fixture\"#\n\vEchoRequest\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\"$\n\fEchoResponse\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value2n\n\vEchoService\x12_\n\x04Echo\x12*.async.grpc.compatible.fixture.EchoRequest\x1A+.async.grpc.compatible.fixture.EchoResponseb\x06proto3"

  # we need to instantiate each entry in the upb pool once to make it available for indirect access
  pool.add_serialized_file(descriptor_data)
rescue Google::Protobuf::TypeError => e
  # TypeError: Unable to build file to DescriptorPool: duplicate file name
  # This happens if the class is loaded twice, safe to ignore
  raise unless e.message.match?(/duplicate file/)
end
pool.lookup("async.grpc.compatible.fixture.EchoRequest").msgclass
pool.lookup("async.grpc.compatible.fixture.EchoResponse").msgclass

# Stub module so Zeitwerk can resolve this file (it expects one constant per file).
module Async
  module Grpc
    module Compatible
      module Fixture
        module CompatibleDescriptor
        end
      end
    end
  end
end
