# rubocop:disable all
# typed: true
# frozen_string_literal: true

# DO NOT EDIT
# Generated by: `protoc-gen-nuevo`
# Source: compatible.proto

require_relative "compatible_descriptor"

# @@protoc_insertion_point(requires)

module Async
  module Grpc
    module Compatible
      module Fixture
        class EchoRequest
          #: -> Symbol?
          def event_class_for_observe
            nil
          end
          # @@protoc_insertion_point(class_definitions)

          #: untyped
          attr_accessor :raw_proto

          #: (?(Hash[untyped, untyped] | untyped)? __value, ?value: String?) -> void
          def initialize(__value = nil, value: nil)
            unless __value
              @raw_proto = EchoRequest.google_proto_class.new(value:)
            else
              __value.transform_keys!(&:to_sym)
              @raw_proto = EchoRequest.google_proto_class.new(__value)
            end
            # @@protoc_insertion_point(initialize)
          end

          #: -> String
          def value
            # @@protoc_insertion_point(get_value)
            @raw_proto["value"]
          end

          #: (String value) -> void
          def value=(value)
            # @@protoc_insertion_point(set_value)
            @raw_proto["value"] = value
          end

          #: ((String | Symbol) key, untyped value) -> void
          def []=(key, value)
            # @@protoc_insertion_point(set_element_operator)
            key = key.to_sym
            case key
            when :value
              return self.value = value
            end
            # @@protoc_insertion_point(set_element_operator_missing)
            raise ArgumentError, "Unknown key: #{key}"
          end

          #: ((String | Symbol) key) -> untyped
          def [](key)
            # @@protoc_insertion_point(get_element_operator)
            key = key.to_sym
            case key
            when :value
              return self.value
            end
            # @@protoc_insertion_point(get_element_operator_missing)
            raise ArgumentError, "Unknown key: #{key}"
          end

          #: -> void
          def clear
            # @@protoc_insertion_point(clear)
            @raw_proto.clear_value
          end
          alias_method :reset, :clear

          #: -> Hash[Symbol, untyped]
          def to_h
            # @@protoc_insertion_point(to_h)
            hash = @raw_proto.to_h
            hash.delete(:value) if @raw_proto["value"].empty?
            hash
          end
          alias_method :to_hash, :to_h

          #: ((String | Symbol) key) -> untyped
          def key?(key)
            # @@protoc_insertion_point(key_predicate)
            key = key.to_sym
            case key
            when :value
              return !@raw_proto["value"].empty?
            end
            raise ArgumentError, "Unknown key: #{key}"
          end
          alias_method :has_key?, :key?
          alias_method :include?, :key?

          #: ((String | Symbol) key) -> untyped
          def delete(key)
            # @@protoc_insertion_point(delete_element_operator)
            key = key.to_sym
            case key
            when :value
              val = self.value
              @raw_proto.clear_value

              @value = nil if instance_variable_defined?(:@value)
              return val
            end
            raise ArgumentError, "Unknown key: #{key}"
          end

          #: (Integer level) -> String
          def _dump(level)
            self.class.encode(self)
          end

          #: (String data) -> EchoRequest
          def self._load(data)
            decode(data)
          end

          #: -> void
          def freeze
            @raw_proto.freeze
          end

          #: -> bool
          def frozen?
            @raw_proto.frozen?
          end

          #: -> EchoRequest
          def dup
            # @@protoc_insertion_point(dup)
            self.class.from(@raw_proto.dup)
          end
          alias clone dup

          #: (untyped other) -> bool
          def eql?(other)
            return false unless self.class == other.class

            @raw_proto.eql?(other.raw_proto)
          end
          alias == eql?

          #: -> Integer
          def hash
            # @@protoc_insertion_point(hash)
            @raw_proto.hash
          end

          #: -> String
          def to_json
            # @@protoc_insertion_point(to_json)
            @raw_proto.to_json
          end

          #: -> String
          def to_proto
            # @@protoc_insertion_point(to_proto)
            @raw_proto.to_proto
          end

          #: -> String
          def inspect
            # @@protoc_insertion_point(inspect)
            @raw_proto.inspect
          end

          #: -> String
          def to_s
            # @@protoc_insertion_point(to_s)
            @raw_proto.to_s
          end
          alias_method :to_str, :to_s

          class << self
            # @@protoc_insertion_point(class_methods)

            #: -> Google::Protobuf::Descriptor
            def descriptor
              EchoRequest.google_proto_class.descriptor
            end

            #: (String data, ?untyped options) -> EchoRequest
            def decode(data, options = {})
              new_instance = allocate
              new_instance.raw_proto = EchoRequest.google_proto_class.decode(data, options)
              new_instance
            end

            #: (EchoRequest message, ?untyped options) -> String
            def encode(message, options = {})
              message.raw_proto.to_proto(options)
            end

            #: (String data, ?untyped options) -> EchoRequest
            def decode_json(data, options = {})
              new_instance = allocate
              new_instance.raw_proto = EchoRequest.google_proto_class.decode_json(data, options)
              new_instance
            end

            #: (EchoRequest message, ?untyped options) -> String
            def encode_json(message, options = {})
              message.raw_proto.to_json(options)
            end

            #Ideally: (Google::Protobuf::AbstractMessage echo_request) -> EchoRequest
            #: (untyped echo_request) -> EchoRequest
            def from(echo_request)
              # @@protoc_insertion_point(from)
              case echo_request
              when EchoRequest
                return echo_request
              when Hash
                return new(echo_request)
              end

              new_instance = allocate
              new_instance.raw_proto = echo_request
              new_instance
            end

            # Ideally: -> singleton(Google::Protobuf::AbstractMessage)
            #: -> untyped
            def google_proto_class
              @google_proto_class ||=
                Google::Protobuf::DescriptorPool
                  .generated_pool
                  .lookup("async.grpc.compatible.fixture.EchoRequest")
                  .msgclass
            end
          end
        end
      end
    end
  end
end
