# rubocop:disable all
# typed: true
# frozen_string_literal: true

# DO NOT EDIT
# Generated by: `protoc-gen-nuevo`
# Source: compatible.proto

require "grpc"
require "nuevo_protobuf/rpc"

require_relative "compatible_descriptor"
require_relative "echo_request"
require_relative "echo_response"
# @@protoc_insertion_point(requires)

module Async
  module Grpc
    module Compatible
      module Fixture
        class EchoService
          class << self
            # Creates a client connected to the specified channel or target
            #
            # channel_name: name of pre-configured channel (e.g., :production, :default)
            # target: direct gRPC server address (e.g., "dns:///service.example.com:443")
            # credentials: ChannelCredentials::Secure or ChannelCredentials::Insecure (required if using target)
            # channel_args: hash of gRPC channel arguments (only used if target is provided)
            # timeout: override default timeout for this client
            #
            # Either channel_name OR target must be provided, but not both
            # If block given, yields client and returns block result; otherwise returns client
            #: (?(String | Symbol)? channel_name, ?target: String?, ?credentials: (NuevoProtobuf::RPC::ChannelCredentials::Secure | NuevoProtobuf::RPC::ChannelCredentials::Insecure)?, ?channel_args: Hash[Symbol, untyped], ?timeout: Numeric?) ?{(EchoService arg0) -> untyped } -> (untyped | EchoService)
            def connected_to(channel_name = nil, target: nil, credentials: nil, channel_args: {}, timeout: nil, &blk)
              raise ArgumentError, "Either channel_name or target must be provided" unless channel_name || target
              raise ArgumentError, "Both channel_name and target cannot be provided" if channel_name && target

              config = NuevoProtobuf::RPC.configuration

              channel =
                if channel_name
                  channel = config.channel_config(channel_name)
                else
                  raise ArgumentError, "Credentials must be provided when specifying a target" unless credentials
                  raise ArgumentError, "Target must be provided" unless target
                  NuevoProtobuf::RPC::Channel.new(target, credentials, channel_args)
                end

              timeout = timeout || config.default_timeout
              propagate_mask = nil

              client = new(channel:, timeout:, propagate_mask:, interceptors: config.client_interceptors)

              if block_given?
                yield client
              else
                client
              end
            end

            #: (Async::Grpc::Compatible::Fixture::EchoRequest request, ?deadline: Time?, ?headers: Hash[Symbol, String]) -> [Async::Grpc::Compatible::Fixture::EchoResponse?, NuevoProtobuf::RPC::ApplicationError?]
            def echo(request, deadline: nil, headers: {})
              client = connected_to(:default)
              client.echo(request, deadline: deadline, headers: headers)
            end
          end

          #: Numeric?
          attr_reader :timeout

          #: (Numeric? timeout) -> void
          def timeout=(timeout)
            @timeout = timeout
            reset_connection_state
          end

          #: (channel: NuevoProtobuf::RPC::Channel, ?timeout: Numeric?, ?propagate_mask: Integer?, ?interceptors: Array[::GRPC::ClientInterceptor]) -> void
          def initialize(channel:, timeout: nil, propagate_mask: nil, interceptors: [])
            @channel = channel
            @timeout = timeout
            @propagate_mask = propagate_mask

            @interceptors = interceptors.dup
            @stub = nil
            @connection_pool = nil
          end

          #: (::GRPC::ClientInterceptor interceptor) -> void
          def add_interceptor(interceptor)
            @interceptors << interceptor
            reset_connection_state
          end

          #: (Async::Grpc::Compatible::Fixture::EchoRequest request, ?deadline: Time?, ?headers: Hash[Symbol, String]) -> [Async::Grpc::Compatible::Fixture::EchoResponse?, NuevoProtobuf::RPC::ApplicationError?]
          def echo(request, deadline: nil, headers: {})
            marshal = ->(req) { req.to_proto }
            unmarshal = Async::Grpc::Compatible::Fixture::EchoResponse.method(:decode).to_proc
            response =
              stub.request_response(
                "/async.grpc.compatible.fixture.EchoService/Echo",
                request,
                marshal,
                unmarshal,
                deadline: deadline,
                **headers,
              )
            [response, nil]
          rescue ::GRPC::BadStatus => e
            error = NuevoProtobuf::RPC::Error.from_grpc(e)
            raise error if error.is_a?(NuevoProtobuf::RPC::ProtocolError)

            [nil, error]
          end

          #: -> void
          def close
            @connection_pool&.close
            @connection_pool = nil
          end

          private

          #: -> void
          def reset_connection_state
            @stub = nil
            @connection_pool&.close
            @connection_pool = nil
          end

          #: -> ::GRPC::ClientStub
          def stub
            if @channel.pooling_enabled?
              # Get a stub from the connection pool
              @connection_pool ||=
                @channel.as_grpc_pool(timeout: @timeout, propagate_mask: @propagate_mask, interceptors: @interceptors)
              @connection_pool.next_stub
            else
              @stub ||=
                ::GRPC::ClientStub.new(
                  @channel.target,
                  nil,
                  channel_override: @channel.as_grpc,
                  timeout: @timeout,
                  propagate_mask: @propagate_mask,
                  interceptors: @interceptors,
                )
            end
          end
        end
      end
    end
  end
end
